spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://localhost:3306/user_service_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: your_mysql_username
    password: your_mysql_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      "[hibernate.format_sql]": true
    open-in-view: false

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

ecommerce:
  security:
    issuer-url: ${ECOMMERCE_SECURITY_ISSUER_URL}
    client-id: ${ECOMMERCE_SECURITY_CLIENT_ID}
    client-secret: ${ECOMMERCE_SECURITY_CLIENT_SECRET}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
