spring:
  application:
    name: user-service

  datasource:
    url: ${USER_DATASOURCE_URL}
    username: ${USER_DATASOURCE_USERNAME}
    password: ${USER_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      "[hibernate.format_sql]": true
    open-in-view: false

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

ecommerce:
  jwt:
    issuer-url: ${ECOMMERCE_JWT_ISSUER_URL}
    expiration-sec: ${ECOMMERCE_JWT_EXPIRATION_SEC}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
